[package]
name = "electrsd"
version = "0.19.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
description = "Utility to run a regtest electrs process, useful in integration testing environment"
repository = "https://github.com/RCasatta/electrsd"
documentation = "https://docs.rs/elecrtsd/"
license = "MIT"
edition = "2018"

[dependencies]
bitcoind = { version = "0.26.0" }
electrum-client = { version="0.8.0", default-features = false }
nix = { version="0.22.0" }
log = "0.4"

[dev-dependencies]
env_logger = "0.9"

[build-dependencies]
bitcoin_hashes = "0.10"
zip = {version = "0.5", default-features = false, features = ["bzip2", "deflate"] }
ureq = "2.1"

[features]
legacy = []

esplora_a33e97e1 = []
electrs_0_8_10 = []
electrs_0_9_1 = []

bitcoind_22_0 = ["bitcoind/22_0"]
bitcoind_0_21_1 = ["bitcoind/0_21_1"]
bitcoind_0_21_0 = ["bitcoind/0_21_0"]
bitcoind_0_20_1 = ["bitcoind/0_20_1"]
bitcoind_0_20_0 = ["bitcoind/0_20_0"]
bitcoind_0_19_1 = ["bitcoind/0_19_1"]
bitcoind_0_19_0_1 = ["bitcoind/0_19_0_1"]
bitcoind_0_18_1 = ["bitcoind/0_18_1"]
bitcoind_0_18_0 = ["bitcoind/0_18_0"]
bitcoind_0_17_1 = ["bitcoind/0_17_1"]
