[package]
name = "electrsd"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
description = "just a placeholder for now"
repository = "https://github.com/RCasatta/electrsd"
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
