[package]
name = "electrsd"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
description = "Utility to run a regtest electrs process, useful in integration testing environment"
repository = "https://github.com/RCasatta/electrsd"
documentation = "https://docs.rs/elecrtsd/"
license = "MIT"
edition = "2018"

[dependencies]
bitcoind = { version = "0.7.0" }
electrum-client = { version="0.7.0", default-features = false }
nix = { version="0.20.0", optional = true }
log = "0.4.14"

[dev-dependencies]
env_logger = "0.8.3"

[features]
trigger = ["nix"]