[package]
name = "electrsd"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
description = "Utility to run a regtest electrs process, useful in integration testing environment"
repository = "https://github.com/RCasatta/electrsd"
documentation = "https://docs.rs/elecrtsd/"
license = "MIT"
edition = "2018"

[dependencies]
bitcoind = { git = "https://github.com/RCasatta/bitcoind", rev="ff0792a3c8317195a65662866727145fde577348" }
electrum-client = { version="0.7.0", default-features = false }
nix = { version="0.20.0", optional = true }
log = "0.4.14"

[dev-dependencies]
env_logger = "0.8.3"

[features]
trigger = ["nix"]

# electrs features
p2p-enabled = [] # requires electrs version >= 0.8.11
monitoring-disabled = [] # requires electrs version >= 0.8.11 built without default features