on:
  workflow_dispatch:

name: Build electrs

jobs:

  build-electrs:
    name: Build Electrs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
    env:
      ELECTRS_TAG: "v0.9.1"

    steps:
      - name: Check out Electrs
        uses: actions/checkout@master
        with:
          repository: romanz/electrs
          ref: ${{ env.ELECTRS_TAG }}
      - name: Build electrs
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: downcase runner.os
        run: echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]' | echo RUNNER_OS_LOWER=$(</dev/stdin) >>${GITHUB_ENV}
      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: electrs_${{ env.RUNNER_OS_LOWER }}_${{ env.ELECTRS_TAG }}
          path: target/release/electrs


  build-electrs-esplora:
    name: Electrs Esplora
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        features: [ "", "--features liquid" ]
    env:
      ELECTRS_COMMIT: "65e20f9e1196c0039d56307b34ea7bcfbe375b99"
    steps:
      - name: Check out Electrs
        uses: actions/checkout@master
        with:
          repository: Blockstream/electrs
          ref: ${{ env.ELECTRS_COMMIT }}
      - name: Build electrs
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release ${{ matrix.features }}
      - name: downcase runner.os
        run: echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]' | echo RUNNER_OS_LOWER=$(</dev/stdin) >>${GITHUB_ENV}
      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: electrs_${{ env.RUNNER_OS_LOWER }}_esplora_${{ env.ELECTRS_COMMIT }}_${{ matrix.features == '' }}
          path: target/release/electrs
