on: [push, pull_request]

name: CI

jobs:

  test-electrs:
    name: Test Electrs
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always
      BITCOIN_VER: 0.21.0
      ELECTRS_VER: 0.8.10
    strategy:
      matrix:
        features: ["", "--features trigger"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        id: cache-step
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
            bitcoin-${{ env.BITCOIN_VER }}
          key: ${{ runner.os }}-test-electrsd-${{ env.BITCOIN_VER }}-${{ env.ELECTRS_VER }}-${{ hashFiles('Cargo.toml','Cargo.lock') }}
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Set ELECTRS_EXE env
        run: echo "ELECTRS_EXE=$HOME/.cargo/bin/electrs" >> $GITHUB_ENV
      - name: Install electrs
        if: steps.cache-step.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: electrs --version ${{ env.ELECTRS_VER }}
      - name: Show electrs options
        run: electrs --help
      - name: Set BITCOIND_EXE env
        run: echo "BITCOIND_EXE=${{ github.workspace }}/bitcoin-${{ env.BITCOIN_VER }}/bin/bitcoind" >> $GITHUB_ENV
      - name: Install bitcoind
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: curl https://bitcoincore.org/bin/bitcoin-core-$BITCOIN_VER/bitcoin-$BITCOIN_VER-x86_64-linux-gnu.tar.gz | tar -xvz bitcoin-$BITCOIN_VER/bin/bitcoind
      - name: Test electrsd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy -- -D warnings

  test-electrs-container:
    name: Test Electrs with container
    runs-on: ubuntu-16.04
    container: bitcoindevkit/electrs:0.4.0
    env:
      BITCOIND_EXE: /root/bitcoind
      ELECTRS_EXE: /root/electrs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bitcoind version
        run: ${BITCOIND_EXE} -version
      - name: Electrs help
        run: ${ELECTRS_EXE} --help
      - name: Install rustup  # cargo action doesn't work inside container
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Test
        run: $HOME/.cargo/bin/cargo test --verbose -- --nocapture