on: [push, pull_request]

name: CI

env:
  BITCOIN_VER: 0.21.0
  ELECTRS_RELEASE_URL: https://github.com/RCasatta/electrsd/releases/download/release_0.3.0

jobs:

  test-electrs:
    name: Test Electrs
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always
      ELECTRS_VER: electrs_ubuntu-20.04_v0.8.10.zip
    strategy:
      matrix:
        features: ["bitcoind_0_21_1", "bitcoind_0_21_1,trigger"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Download electrs
        run: wget ${{ env.ELECTRS_RELEASE_URL }}/${{ env.ELECTRS_VER }} && unzip ${{ env.ELECTRS_VER }} && chmod +x ./electrs
      - name: Set ELECTRS_EXE env
        run: echo "ELECTRS_EXE=${{ github.workspace }}/electrs" >> $GITHUB_ENV
      - name: Show electrs options
        run: ${{ env.ELECTRS_EXE }} --help
      - name: Test electrsd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features ${{ matrix.features }}


  test-electrs-esplora:
    name: Test Electrs Esplora
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always
      ELECTRS_VER: electrs_esplora_ubuntu-20.04_a33e97e1a1fc63fa9c20a116bb92579bbf43b254.zip
    strategy:
      matrix:
        features: ["bitcoind_0_21_1,legacy"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Download electrs
        run: wget ${{ env.ELECTRS_RELEASE_URL }}/${{ env.ELECTRS_VER }} && unzip ${{ env.ELECTRS_VER }} && chmod +x ./electrs
      - name: Set ELECTRS_EXE env
        run: echo "ELECTRS_EXE=${{ github.workspace }}/electrs" >> $GITHUB_ENV
      - name: Show electrs options
        run: ${{ env.ELECTRS_EXE }} --help
      - name: Test electrsd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features ${{ matrix.features }}


  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy -- -D warnings

