on: [push, pull_request]

name: CI

jobs:

  test-electrs:
    name: Test Electrs
    runs-on: ubuntu-16.04
    container: bitcoindevkit/electrs
    env:
      BITCOIND_EXE: /root/bitcoind
      ELECTRSD_EXE: /root/electrsd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose